version: "3.9"

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - appnet

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: fizzbuzz-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8080   # or http://localhost:8080 when running locally
    depends_on:
      - api
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
